#HUAWEI-PN (JOBS-V3)
#DEPLOYMENT
fullnameOverride: hms-gorush
nameOverride: hms-gorush
replicaCount: 10
tier: frontend
namespace: gorush

image:
  repository: asia-southeast1-docker.pkg.dev/bustling-sunset-220007/newswav-gorush/newswav-gorush
  tag: latest

appEnv:
- name: GORUSH_IOS_ENABLED
  value: "false"
- name: GORUSH_ANDROID_ENABLED
  value: "false"
  
resources:
  limits:
    memory: 500Mi
    cpu: "500m"
  requests:
    memory: 10Mi
    cpu: "5m"

readinessProbe:
  httpGet:
    path: /healthz
    port: 8088
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 10

livenessProbe:
  httpGet:
      path: /healthz
      port: 8088
  initialDelaySeconds: 5
  periodSeconds: 60
  timeoutSeconds: 30

envFrom:
  - configMapRef:
      name: gorush-config
  - secretRef:
      name: gorush-gcpsm

appContainerPort: 8088

#SERVICE
service:
  enabled: true
  type: NodePort
  port: 80

#ingress
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: hms-gorush-ingress-ip
  tls: 
   -  secretName: ssl-wildcard-newswav
      hosts:
        - hms-gorush.newswav.com

  hosts:
  - host: hms-gorush.newswav.com
    paths:
      - path: /
        pathType: Prefix